pipeline {
    agent any
    environment {
        JAVA_HOME = '/opt/java/jdk-21'
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Start') { 
            steps {
                echo "First stage started and see what next!" 
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('Completed') { 
            steps {
                echo "Completed the Build Successfully !!!" 
            }
        }
    }
}
